[project]
name = "ansible-home-network"
version = "1.0.0"
description = "Ansible configuration for the home network @seb"
requires-python = ">=3.13,<3.14"
dependencies = [
    "ansible>=10"
]

[tool.uv]
python-preference = "only-managed"
