- name: systemd-daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: systemd-resolved-restart
  become: true
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: restarted

- name: pi-hole-restart
  ansible.builtin.systemd_service:
    name: pi-hole
    state: restarted
