- name: Reboot system
  ansible.builtin.reboot:
    reboot_timeout: 600

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart systemd-resolved
  become: true
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: restarted

- name: Restart Pi-Hole container
  become: true
  ansible.builtin.systemd_service:
    name: pi-hole
    state: restarted
